### PR TITLE
Fixed typos and corrected Grammar

### PR DESCRIPTION
**Pull request by knight-95**
Added punctuations wherever necessary, fixed typos

### CODE REVIEW

**Comment by knight-95** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
@rohnsha0 Why did you close this pull request?

**Comment by rohnsha0** [comment]
@davisagli As I've already done the same thing... As well as corrected Discord link.... So I thought that it won't make any sense...
Nevertheless, if it wasn't to be done... I apologise!

**Comment by davisagli** [comment]
@rohnsha0 oh okay, I didn't see your pull request #23

**Comment by rohnsha0** [comment]
@davisagli #23  it is open for review!

**Pull request closed without merging**
